using WebApplication1.Areas.Identity.Models;
using WebApplication1.Data.Entities;
using WebApplication1.Models;

namespace WebApplication1.Mappings;
public static class UserExtensions
{
    public static User ToEntity(this RegisterViewModel viewModel)
    {
        return new User
        {
            //Id is a guid autogenerated
            UserName = viewModel.Email,
            Email = viewModel.Email,
            Name = viewModel.Name!,
            LastName = viewModel.LastName!,
            IsActive = viewModel.IsActive
        };
    }    

    public static UserViewModel ToViewModel(this User entity)
    {
        return new UserViewModel
        {
            Id = entity.Id,
            Name = entity.Name!,
            LastName = entity.LastName!,
            Email = entity.Email,
            PhoneNumber = entity.PhoneNumber,
            LockoutEnd = entity.LockoutEnd,
            IsActive = entity.IsActive
        };
    }
}

